# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813504d1ef27d302b49a30088df19366dd3053d920a79c954b5a5406cac5dac6b67b9b892103a7dee56d8140794c9033b5a8c19bb6b363b85e7017ca8756bbac
  google_app_id: 321166250838-raeovir3ar73jbgk52qe7bmtiun1blnt.apps.googleusercontent.com
  google_app_secret: mpLLKR3zQeaJQ0BUeRct36sk
  github_app_id: 69db621bef816973e29f
  github_app_secret: ba9cb6af98706c45e2a8ff47f14c86ca726701a5

test:
  secret_key_base: b17e45fccab43362b51a2fcd9731c22a16505919411ce586692f67f4beeca09a8ee2b7e3dd5045dff0f6ebe116c820c9bed858018b4befa7434862a59e705a4f
  google_app_id: 852923023707-bgv2dco3d0s41v8t77flu2dmet7upg07.apps.googleusercontent.com
  google_app_secret: VA_ewt5iJU4HXJ0TEApRKjaW

# Do not keep production secrets in the repository,
# instead read values from the environment.

qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV['GOOGLE_APP_SECRET'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV['GOOGLE_APP_SECRET'] %>